INSERT INTO habitaciones (descriccion, tipo, estado) VALUES('1-A', 'ESTANDAR', 'LIBRE');
INSERT INTO habitaciones (descriccion, tipo, estado) VALUES('1-B', 'ESTANDAR', 'MANTENIMIENTO');
INSERT INTO habitaciones (descriccion, tipo, estado) VALUES('1-C', 'ESTANDAR', 'LIBRE');
INSERT INTO habitaciones (descriccion, tipo, estado) VALUES('2-A', 'NORMAL', 'LIBRE');
INSERT INTO habitaciones (descriccion, tipo, estado) VALUES('2-B', 'NORMAL', 'OCUPADA');
INSERT INTO habitaciones (descriccion, tipo, estado) VALUES('2-C', 'ESTANDAR', 'OCUPADA');
INSERT INTO habitaciones (descriccion, tipo, estado) VALUES('3-A', 'SUITE', 'LIBRE');
INSERT INTO habitaciones (descriccion, tipo, estado) VALUES('3-B', 'SUITE', 'MANTENIMIENTO');
INSERT INTO habitaciones (descriccion, tipo, estado) VALUES('3-C', 'SUITE', 'OCUPADA');